### ISSUE TITLE
Monolingual Treebanks for Polyglot Parsing 

### ISSUE THREAD

**Issue by Mounika2405** [irshadbhat/csnlp#3]
Hi,

I'm trying to run the polyglot parser but it seems like there's some issue with the version of monolingual treebanks. I've tried with Version 1.4 and Version 2 UD treebanks. Can anyone please help me fix the issue?

Command Used:
python polyglot_jm_parser.py --etrain csnlp-master/ud-treebanks-v2.4/UD_English-LinES/en_lines-ud-train.conllu --edev csnlp-master/ud-treebanks-v2.4/UD_English-LinES/en_lines-ud-dev.conllu --htrain csnlp-master/ud-treebanks-v1.4/UD_Hindi/hi-ud-train.conllu --hdev csnlp-master/ud-treebanks-v1.4/UD_Hindi/hi-ud-dev.conllu --cdev UD_Hindi_English-master/tweets_dev.conll --hi-embds UD_Hindi_English-master/pretrained_embeddings/hi/  --trainer adam --bvec 1 --save UD_Hindi_English-master/models/

<img width="1150" alt="Screenshot 2020-01-03 at 12 42 00 PM" src="https://user-images.githubusercontent.com/33863436/71711313-7a143100-2e26-11ea-94b2-e933645d338b.png">

Thanks,
Mounika K.

**Comment by irshadbhat** [comment]
I guess the error is due to the `#` lines in UD files. I have updated the code (check line 450). Try again and see if it works.

**Comment by Mounika2405** [comment]
Thanks, that works :)
